# Generated by Django 5.1.4 on 2025-01-24 01:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcv', '0004_cv_design_cv_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Associer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcv.cv')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcv.formation')),
            ],
        ),
        migrations.CreateModel(
            name='Inclure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcv.cv')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcv.experience')),
            ],
        ),
        migrations.CreateModel(
            name='Posseder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcv.competence')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rajouter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcv.cv')),
                ('langue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcv.langue')),
            ],
        ),
    ]
